### ISSUE TITLE
Add CSS grid documentation 

### ISSUE THREAD

**Issue by RakshithNM** [MoonHighway/css-layout#1]

**Comment by eveporcello** [comment]
Hi - thanks for the issue here! These are the files for a CSS class that we developed several years ago... prior to CSS Grid being released. We'll plan to update next time we teach this course. 

In the meantime, here are some great resources about CSS Grid:
* [Grid By Example](https://gridbyexample.com/)
* [Learn CSS Grid](http://learncssgrid.com/)
* [MDN Docs](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Grid_Layout)
